[package]
name = "asc-logging"
version = "0.1.0"
edition = "2021"

[dependencies]
asc-types = { path = "../asc-types" }
hex = { workspace = true }
serde = { workspace = true }
serde_json = "1"
sha2 = { workspace = true }
